@echo off 
IF "%srcpath%" == "" (
    echo srcpath is not defined please set both srcpath and dstpath
    goto GracefulExit
)
IF "%dstpath%" == "" (
    echo dstpath is not defined please set both srcpath and dstpath
    goto GracefulExit
)
echo %srcpath% to %dstpath%
echo "chrome\browser"
xcopy "%srcpath%\src\chrome\browser\about_flags.cc"  "%dstpath%\src\chrome\browser\*"
xcopy "%srcpath%\src\chrome\browser\flag_descriptions.cc"  "%dstpath%\src\chrome\browser\*"
xcopy "%srcpath%\src\chrome\browser\flag_descriptions.h"  "%dstpath%\src\chrome\browser\*"
xcopy "%srcpath%\src\chrome\browser\flag-metadata.json"  "%dstpath%\src\chrome\browser\*"
echo "content\browser\device_service"
xcopy "%srcpath%\src\content\browser\device_service\device_service_browsertest.cc" "%dstpath%\src\content\browser\device_service\*"
echo "content\browser"
xcopy "%srcpath%\src\content\browser\browser_interface_binders.cc" "%dstpath%\src\content\browser\*"
xcopy "%srcpath%\src\content\browser\browser_interface_binders.h" "%dstpath%\src\content\browser\*"

echo "content\child"
xcopy "%srcpath%\src\content\child\runtime_features.cc" "%dstpath%\src\content\child\*"
echo "content\public\common"
xcopy "%srcpath%\src\content\public\common\content_features.cc" "%dstpath%\src\content\public\common\*"
xcopy "%srcpath%\src\content\public\common\content_features.h" "%dstpath%\src\content\public\common\*"
echo "services\device\device_service"
xcopy "%srcpath%\src\services\device\device_service\BUILD.gn" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_platform_provider_win.cc" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_platform_provider_win.h" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_platform_provider.cc" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_platform_provider.h" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_provider_impl.cc" "%dstpath%\src\services\device\device_service\*"
xcopy "%srcpath%\src\services\device\device_service\device_service_provider_impl.h" "%dstpath%\src\services\device\device_service\*"
echo "services\device\public\cpp\test"
xcopy "%srcpath%\src\services\device\public\cpp\test\fake_device_service_provider.cc" "%dstpath%\src\services\device\public\cpp\test\*"
xcopy "%srcpath%\src\services\device\public\cpp\test\fake_device_service_provider.h" "%dstpath%\src\services\device\public\cpp\test\*"
echo "services\device\cpp"
xcopy "%srcpath%\src\services\device\public\cpp\BUILD.gn" "%dstpath%\src\services\device\public\cpp\*"
echo "services\device\public\mojom"
xcopy "%srcpath%\src\services\device\public\mojom\BUILD.gn" "%dstpath%\src\services\device\public\mojom\*"
xcopy "%srcpath%\src\services\device\public\mojom\device_service_provider.mojom" "%dstpath%\src\services\device\public\mojom\*"
xcopy "%srcpath%\src\services\device\public\mojom\device_service.mojom" "%dstpath%\src\services\device\public\mojom\*"
echo "services\device"
xcopy "%srcpath%\src\services\device\BUILD.gn" "%dstpath%\src\services\device\*"
xcopy "%srcpath%\src\services\device\device_service.cc" "%dstpath%\src\services\device\*"
xcopy "%srcpath%\src\services\device\device_service.h" "%dstpath%\src\services\device\*"
echo "third_party\blink\public\common\privacy_budget"
xcopy "%srcpath%\src\third_party\blink\public\common\privacy_budget\identifiable_surface.h" "%dstpath%\src\third_party\blink\public\common\privacy_budget\*"
echo "third_party\blink\render\bindings"
xcopy "%srcpath%\src\third_party\blink\renderer\bindings\generated_in_modules.gni" "%dstpath%\src\third_party\blink\renderer\bindings\*"
xcopy "%srcpath%\src\third_party\blink\renderer\bindings\idl_in_modules.gni" "%dstpath%\src\third_party\blink\renderer\bindings\*"
echo "third_party\blink\renderer\core\css\parser"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\parser\media_query_parser.cc" "%dstpath%\src\third_party\blink\renderer\core\css\parser\*"
echo "third_party\blink\renderer\core\css"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_feature_names.json5" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_query_evaluator.cc" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_query_exp.cc" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values_cached.cc" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values_cached.h" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values_dynamic.cc" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values_dynamic.h" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values.cc" "%dstpath%\src\third_party\blink\renderer\core\css\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\css\media_values.h" "%dstpath%\src\third_party\blink\renderer\core\css\*"
echo "third_party\blink\renderer\core\frame"
xcopy "%srcpath%\src\third_party\blink\renderer\core\frame\local_frame_mojo_handler.cc" "%dstpath%\src\third_party\blink\renderer\core\frame\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\frame\local_frame_mojo_handler.h" "%dstpath%\src\third_party\blink\renderer\core\frame\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\frame\local_frame.cc" "%dstpath%\src\third_party\blink\renderer\core\frame\*"
xcopy "%srcpath%\src\third_party\blink\renderer\core\frame\local_frame.h" "%dstpath%\src\third_party\blink\renderer\core\frame\*"
echo "third_party\blink\renderer\modules\device_service"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\BUILD.gn" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\DEPS" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\device_service.cc" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\device_service.h" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\device_service.idl" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\DIR_METADATA" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\navigator_device_service.cc" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\navigator_device_service.h" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\navigator_device_service.idl" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\device_service\README.md" "%dstpath%\src\third_party\blink\renderer\modules\device_service\*"
echo "third_party\blink\renderer\modules"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\BUILD.gn" "%dstpath%\src\third_party\blink\renderer\modules\*"
xcopy "%srcpath%\src\third_party\blink\renderer\modules\event_target_modules_names.json5" "%dstpath%\src\third_party\blink\renderer\modules\*"
echo "third_party\blink\renderer\platform\scheduler\"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\scheduler\BUILD.gn" "%dstpath%\src\third_party\blink\renderer\platform\scheduler\common\*"
echo "third_party\blink\renderer\platform\scheduler\common\"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\scheduler\common\thread_load_tracker.cc" "%dstpath%\src\third_party\blink\renderer\platform\scheduler\common\*"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\scheduler\common\thread_load_tracker.orig.cc" "%dstpath%\src\third_party\blink\renderer\platform\scheduler\common\*"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\scheduler\common\device_capacity.cc" "%dstpath%\src\third_party\blink\renderer\platform\scheduler\common\*"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\scheduler\common\device_capacity.h" "%dstpath%\src\third_party\blink\renderer\platform\scheduler\common\*"
echo "third_party\blink\renderer\platform\"
xcopy "%srcpath%\src\third_party\blink\renderer\platform\runtime_enabled_features.json5" "%dstpath%\src\third_party\blink\renderer\platform\*"
:GracefulExit
